services:
  - type: web
    name: deepthinks-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 --workers 2 --worker-class gevent --timeout 120 --keepalive 5 --worker-connections 1000 app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APP_KEY
        sync: false
      - key: B2_BUCKET_NAME
        value: deepthinks-files
      - key: B2_ENDPOINT
        value: https://s3.us-west-004.backblazeb2.com
      - key: TOGETHER_KEY_ENC_KEY
        sync: false
